# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pr:
- master
- releases/*
- feature/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'npm build'

- script: |
    npm run test:unit
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: 'npm test unit'

- script: |
    rm .env.test
    set DB_HOST=$(Build.DB_HOST)
    set DB_DATABASE=$(Build.DB_DATABASE)
    set DB_USER=$(Build.DB_USER)
    set DB_PASSWORD=$(Build.DB_PASSWORD)
    set
  displayName: Set DotEnv variables
  env:
    ANOTHER_DOTENV_PROP: someValue

- script: |
    npm run test:integration
    if [ $? -ne 0 ]; then
      exit 1
    fi
  displayName: 'npm test integration'
