# Check out https://hub.docker.com/_/node to select a new base image
FROM node:10-slim

WORKDIR /share

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY --chown=node package*.json ./

RUN npm ci

COPY ./ /share

RUN cd /share && npm run build

RUN cp -r /share/dist/. /share/

# Bind to all network interfaces so that it can be mapped to the host OS
EXPOSE 8080

CMD node ./index.js