version: '3'
services:
  db:
    image: postgres
    container_name: node-graphql-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - node-graphql-api
    expose:
      - 5432
    ports:
      - 5432:5432

  app:
    container_name: node-graphql-app
    build:
      context: ./
      dockerfile: Dockerfile.prod
    stdin_open: true
    networks:
      - node-graphql-api
    volumes:
      - .:/share
    ports:
      - 9090:9090
    depends_on:
      - db

networks:
  node-graphql-api:

volumes:
  postgres-data:
