version: '3.3'
services:
  db:
    image: gabrielcodelitt.azurecr.io/postgres:latest
    environment:
      POSTGRES_DB: node_graphql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
  app:
     image: gabrielcodelitt.azurecr.io/nodestartercodelitt_app:latest
     ports:
       - "80:8080"
     restart: always
     environment:
       SERVER_PORT: 8080
       DB_HOST: db
       DB_DATABASE: node_graphql
       DB_USER: postgres
       DB_PASSWORD: postgres
     depends_on:
       - db